#!/usr/bin/env python

import sys
import mercy.importers.fda

startIdx = 0
if ( len(sys.argv) >= 3 ):
    startIdx = int(sys.argv[2])

sys.exit(mercy.importers.fda.FDAImporter().read(sys.argv[1], startIdx=startIdx))
